name: 'Restore STK CLI cache'
description: 'Restore cache action'


inputs:
  stk:
    description: stk cli name
    required: true

runs:
  using: "composite"
  steps:
    - id: cache-execution
      name: Cache STK installation
      uses: actions/cache@v3
      with:
        key: stk-cache-execution-${{ inputs.stk }}-${{github.run_id}}
        path: |
          ~/.${{ inputs.stk }}
    - name: Configure path
      if: steps.cache-execution.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "PATH=$PATH:~/.${{ inputs.stk }}/bin" >> $GITHUB_ENV
        echo "STK_CLI_TEST=true" >> $GITHUB_ENV
