name: 'Clone external repository'
description: 'Clone external GitHub repository'
inputs:
  app_name:
    description: App name
    required: true
  github_org:
    description: GitHub Organization slug
    required: true
  path:
    description: Path to clone repository
    required: true
  secret_git_token:
    description: 'A Github token (pat or jwt)'
    required: true
  github_url:
    description: GitHub URL if exists repository
    required: false
  default_branch:
    description: Default Branch
    required: true

outputs:
  repo:
    description: repo in format organization/repository_name
    value: ${{ steps.new_repo.outputs.REPO }}${{ steps.existing_repo.outputs.REPO }}

runs:
  using: "composite"
  steps:
    - id: new_repo
      name: New repo url value
      shell: bash
      if: inputs.github_url == ''
      run: |
        echo "REPO=${{ inputs.github_org }}/${{inputs.app_name }}" >> $GITHUB_ENV
        echo "REPO=${{ inputs.github_org }}/${{inputs.app_name }}" >> $GITHUB_OUTPUT
    - id: existing_repo 
      name: Existing url value
      shell: bash
      if: inputs.github_url != ''
      run: |
        url=$(echo -n "${{inputs.github_url }}" | sed 's/.*github.com\///')
        echo "REPO=$url"  >> $GITHUB_ENV
        echo "REPO=$url"  >> $GITHUB_OUTPUT
    - name: Clone repo
      shell: bash
      run: |
        git clone https://${{inputs.secret_git_token}}@github.com/${{ env.REPO }} ${{ inputs.path }}
        cd ${{ inputs.path }}
        git checkout ${{inputs.default_branch}} || git checkout -b ${{inputs.default_branch}}